---
title: "UTAG"
output: html_document
date: '2022-05-24'
---

```{r setup, include=FALSE}
#install.packages('reticulate')
library(reticulate)

use_condaenv('utag')
pd = import('pandas', as = 'pd')
#system('pip3 install git+https://github.com/ElementoLab/utag.git@main')
```

```{r}
print('Hello World')
pd = import('pandas', as = 'pd', convert = FALSE)

#import pandas
#import anndata

```

```{python}
from utag import utag

# Use Scanpy to get a h5ad file with provided data
import scanpy as sc
adata = sc.read(
    'data/healthy_lung_adata.h5ad',
    backup_url='https://zenodo.org/record/6376767/files/healthy_lung_adata.h5ad?download=1')

# Run UTAG on provided data
utag_results = utag(
    adata,
    slide_key="roi",
    max_dist=20,
    normalization_mode='l1_norm',
    apply_clustering=True,
    clustering_method = 'leiden', 
    resolutions = [0.05, 0.1, 0.3]
)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
